# Generated by Django 4.0.4 on 2022-05-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0004_alter_categoryexpenses_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.CharField(help_text='Enter the name of the Income', max_length=100, unique=True, verbose_name='Name of Income')),
                ('summ_income', models.DecimalField(decimal_places=2, help_text='Enter the amount in $', max_digits=20, null=True, verbose_name='Amount in $')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Date Income')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.categoryincome', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Planning Income',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlanningExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.CharField(help_text='Enter the name of the Expenses', max_length=100, unique=True, verbose_name='Name of Expenses')),
                ('summ_expenses', models.DecimalField(decimal_places=2, help_text='Enter the amount in $', max_digits=20, null=True, verbose_name='Amount in $')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Date Expenses')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.categoryexpenses', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Planning Expenses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ_expenses', models.DecimalField(decimal_places=2, help_text='Enter the amount in $', max_digits=20, null=True, verbose_name='Amount in $')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Budget date')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.categoryexpenses', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Budget',
                'ordering': ['id'],
            },
        ),
    ]
