# Generated by Django 4.0.4 on 2022-05-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Budget date'),
        ),
    ]
