# Generated by Django 4.0.4 on 2022-05-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(help_text='Enter the name of the Account', max_length=100, null=True, verbose_name='Name of Account')),
            ],
            options={
                'verbose_name': 'Account',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Enter the name of the Tag', max_length=100, null=True, verbose_name='Name of Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoryincome',
            options={'ordering': ['id'], 'verbose_name': 'Category'},
        ),
        migrations.RemoveField(
            model_name='categoryincome',
            name='name_income',
        ),
        migrations.AddField(
            model_name='categoryincome',
            name='category',
            field=models.CharField(help_text='Enter the name of the Category', max_length=100, null=True, verbose_name='Name of Category'),
        ),
    ]
