# Generated by Django 4.0.4 on 2022-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_account_tag_alter_categoryincome_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Enter the name of the Category', max_length=100, null=True, verbose_name='Name of Category')),
            ],
            options={
                'verbose_name': 'Category',
                'ordering': ['id'],
            },
        ),
    ]
