# Generated by Django 4.0.4 on 2022-05-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_categoryexpenses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryexpenses',
            options={'ordering': ['id'], 'verbose_name': 'Category Expenses'},
        ),
        migrations.AlterModelOptions(
            name='categoryincome',
            options={'ordering': ['id'], 'verbose_name': 'Category Income'},
        ),
    ]
