# Generated by Django 4.0.4 on 2022-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_categoryexpenses_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CSH', 'Cash'), ('DBT', 'Debit'), ('CRD', 'Credit'), ('SAC', 'Savings Account')], max_length=4, verbose_name='Account Type'),
        ),
    ]
