# Generated by Django 4.0.4 on 2022-05-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_income_delete_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the name of the income', max_length=100, unique=True, verbose_name='Name of expenses')),
            ],
            options={
                'verbose_name': 'Expenses',
                'ordering': ['id'],
            },
        ),
    ]
