# Generated by Django 4.0.4 on 2022-05-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_expenses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Income'},
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='title',
            new_name='category',
        ),
    ]
