# Generated by Django 4.0.4 on 2022-05-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_expenses_options_alter_income_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='title',
            new_name='category',
        ),
    ]
