# Generated by Django 4.0.4 on 2022-05-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_title_income_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Enter the name of the income', max_length=100, unique=True, verbose_name='Name of expenses')),
            ],
            options={
                'verbose_name': 'Transfer',
            },
        ),
    ]
