# Generated by Django 4.0.4 on 2022-05-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['id'], 'verbose_name': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['id'], 'verbose_name': 'Income'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['id'], 'verbose_name': 'Transfer'},
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='category',
            new_name='name_expenses',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='category',
            new_name='name_income',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='category',
            new_name='name_transer',
        ),
    ]
