# Generated by Django 4.0.4 on 2022-05-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('transactions', '0007_alter_expenses_options_alter_income_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='category_income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.categoryincome', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='income',
            name='summ_income',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Enter the amount in $', max_digits=20, verbose_name='Amount in $'),
            preserve_default=False,
        ),
    ]
