# Generated by Django 4.0.4 on 2022-05-05 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_categoryexpenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0010_income_account_income_date_income_img_income_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='category_expenses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.categoryexpenses', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Transaction date'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='img',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='status',
            field=models.CharField(choices=[('CNFD', 'Confirmed'), ('NCNF', 'Not confirmed'), ('WTNG', 'Waiting')], default='CNFD', max_length=4, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='summ_expenses',
            field=models.DecimalField(decimal_places=2, help_text='Enter the amount in $', max_digits=20, null=True, verbose_name='Amount in $'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='name_expenses',
            field=models.CharField(help_text='Enter the name of the expenses', max_length=100, unique=True, verbose_name='Name of expenses'),
        ),
        migrations.AlterField(
            model_name='income',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.tag', verbose_name='Tag'),
        ),
    ]
