# Generated by Django 4.0.4 on 2022-05-05 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0004_alter_categoryexpenses_options_and_more'),
        ('transactions', '0011_expenses_account_expenses_category_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='name_transer',
        ),
        migrations.AddField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Transaction date'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_account', to='settings.account', verbose_name='From Account'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='summ_transfer',
            field=models.DecimalField(decimal_places=2, help_text='Enter the amount in $', max_digits=20, null=True, verbose_name='Amount in $'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_account', to='settings.account', verbose_name='To Account'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='income',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
