# Generated by Django 4.0.4 on 2022-05-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_account_account_type'),
        ('transactions', '0012_remove_transfer_name_transer_transfer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.CharField(blank=True, choices=[('CNFD', 'Confirmed'), ('NCNF', 'Not confirmed'), ('WTNG', 'Waiting')], default='CNFD', max_length=4, null=True, verbose_name='Status'),
        ),
    ]
