# Generated by Django 4.0.4 on 2022-05-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_expenses_account_alter_expenses_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Income'},
        ),
    ]
