# Generated by Django 4.0.4 on 2022-05-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_income_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['id'], 'verbose_name': 'Income'},
        ),
    ]
